### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by jbelien** [oSoc19/cycling-up-frontend#68]
Let's define each slide the final website will have!

- [x] Slide(s) with historical (map + chart) #65 
- [x] Slide with infrastructures/services (map) #66 
- [x] Slide with bike count (map + chart) #67
- [x] Slide with Villo! stations (map + chart) #70 
- [x] Slide with commute to work (chart) #71
